---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Steve.
--- DateTime: 16/12/2020 15:06
---

function Update(I)
    I:ClearLogs()

    buildArms(I)

end

function buildWings(I)
    local wings = {}

    local subConstructs = I:GetAllSubConstructs()

    --logSubConstructs(subConstructs)
    I:Log(string.format('exploring %d subconstructs', #subConstructs))
    for i = 1, #subConstructs do
        if I:IsSpinBlock(subConstructs[i]) then
            if I:IsSubConstructOnHull(subConstructs[i]) then
                wings[subConstructs[i]] = Wing.new(I, subConstructs[i])
            end
        end
    end

    return wings
end

Wing = {
    new = function(I, scId)
        local scV = I:GetSubConstructInfo(scId)
        local scD = nil
        local scChildren = I:GetAllSubConstructChildren(scV.SubConstructIdentifier)
        if (#scChildren ~= 1) then
            error('not a leg')
        else
            scD = I:GetSubConstructInfo(scChildren[1])
        end
        return {
            cps = 10,
            spinVid = scId,
            spinDid = scD,
            curStep = 0,
            move = function(self, I, time)
                local step = ((time * self.cps) % 1) * 4
                if step > 3 then

                elseif step > 2 then
                elseif step > 1 then
                else -- step between 0 and 1

                end
            end

        }
    end
}